### ISSUE TITLE
X-overflow on Ubuntu/FF 66.0

### ISSUE THREAD

**Issue by robinmetral** [gillkyle/gatsby-starter-landing-page#5]
Hey @gillkyle, 👏 for the starter!

I just noticed x-overflow on the demo:

![Capture du 2019-05-18 09-03-57](https://user-images.githubusercontent.com/35560568/57966008-9c674600-794c-11e9-85bd-970bda2ca849.png)

User agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0

**Comment by gillkyle** [comment]
Ooh thanks for pointing this out @robinmetral, I haven't been good at testing other browsers. I'll try and fix this soon 🙂

**Comment by robinmetral** [comment]
I get it, browser testing is hard!

I keep stumbling on this kind of things with my unusual browser agent, even on large apps and websites (including GitHub! :stuck_out_tongue:)

**Comment by gillkyle** [comment]
I still haven't ever gotten around to looking into this so closing for now.
